apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    app.openshift.io/route-disabled: "false"
    app.openshift.io/vcs-ref: playground
    app.openshift.io/vcs-uri: https://github.com/uh-dcm/news-article-collection-container
    deployment.kubernetes.io/revision: "11"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"news-collection-playground:latest","namespace":"news-container"},"fieldPath":"spec.template.spec.containers[?(@.name==\"news-collection-playground\")].image","pause":"false"}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"app.openshift.io/route-disabled":"false","app.openshift.io/vcs-ref":"playground","app.openshift.io/vcs-uri":"https://github.com/uh-dcm/news-article-collection-container"},"labels":{"app":"news-collection-playground","app.kubernetes.io/component":"news-collection-playground","app.kubernetes.io/instance":"news-collection-playground","app.kubernetes.io/name":"news-collection-playground","app.kubernetes.io/part-of":"news-collection-app"},"name":"news-collection-playground","namespace":"news-container"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"news-collection-playground"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"news-collection-playground"}},"spec":{"containers":[{"image":"image-registry.openshift-image-registry.svc:5000/news-container/news-collection-playground:latest","imagePullPolicy":"Always","name":"news-collection-playground","volumeMounts":[{"mountPath":"/app/server/rss-fetcher/data","name":"data-playground"}]}],"volumes":[{"name":"data-playground","persistentVolumeClaim":{"claimName":"data-playground"}}]}}}}
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2024-06-17T13:41:44Z"
  generation: 16
  labels:
    app: news-collection-playground
    app.kubernetes.io/component: news-collection-playground
    app.kubernetes.io/instance: news-collection-playground
    app.kubernetes.io/name: news-collection-playground
    app.kubernetes.io/part-of: news-collection-app
  name: news-collection-playground
  namespace: news-container
  resourceVersion: "165994432"
  uid: ceccf281-87e7-47b4-88ba-846f0874c3f2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: news-collection-playground
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-06-24T18:14:51+03:00"
        openshift.openshift.io/restartedAt: "2024-06-17T15:14:26.366Z"
      creationTimestamp: null
      labels:
        app: news-collection-playground
        deployment: news-collection-playground
    spec:
      containers:
        - image: docker.io/yyrsi/news-collection-playground@sha256:8d1c4b1a1bfef4b2d18f54e002703100aa3127a3f3f2882fe145bb02b82dd7b1
          imagePullPolicy: Always
          name: news-collection-playground
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/server/rss-fetcher/data
              name: data-playground
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data-playground
          persistentVolumeClaim:
            claimName: data-playground
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2024-06-24T17:03:25Z"
      lastUpdateTime: "2024-06-24T17:03:25Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-06-24T14:58:52Z"
      lastUpdateTime: "2024-06-24T17:03:25Z"
      message: ReplicaSet "news-collection-playground-5d4dfbf948" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
