apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: news-collection
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker.io/ohtukontitus/news-collection:latest
      generation: 4
      importPolicy:
        importMode: Legacy
        scheduled: true
      name: latest
      referencePolicy:
        type: Source