apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-prod
spec:
  capacity:
      storage: 1Gi
  storageClassName: standard-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi