# Important:
# Meant to be ran locally for example with 'act'
# to run work flow input the following command (assuming act is installed):
# act -j local

name: local build

on:
  workflow_dispatch:

jobs:
  local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.5.1"

      - name: Install Node dependencies
        run: |
          cd client
          npm install

      - name: Lint the TypeScript code
        run: |
          cd client
          npm run lint

      - name: Run Vitest tests
        run: |
          cd client
          npm test

      - name: Build the client
        run: |
          cd client
          npm run build

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt -r server/requirements-dev.txt

      - name: Lint the Python code
        run: |
          pylint --recursive=y --fail-under=7 server/src

      - name: Run Python tests
        run: |
          cd server
          pytest

      - name: Docker Compose
        run: docker compose up --build -d

      - name: Wait for container to build
        run: sleep 10

      - name: Docker compose down
        run: docker compose down

    # Cypress tests failed to work
    # Should be added but require some debugging
    # Issue could be ARM-related
